version: '2'

services:

  wikibot:
    image: eaudeweb/redmine.wikibot
    container_name: redmine-wikibot
    volumes:
         - "./env-wikibot:/env-wikibot"
    command: python3 listcontainers.py 
    #command: tail -f /dev/null
